services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

#  mongodb:
#    image: mongo:latest
#    container_name: mongodb
#    ports:
#      - 27017:27017
#    deploy:
#      resources:
#        limits:
#          cpus: "0.13"
#          memory: "140MB"
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./docker/start.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api01: &api
    build:
      context: .
    hostname: api01
    ports:
      - 8081:8080
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=rinha2024q1
#      - MONGO_URI=mongodb:27017
#      - DATABASE_NAME=rinha
#      - COLLECTION_NAME=customers
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - 8082:8080

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1